language: java
sudo: false
jdk:
- oraclejdk8
git:
  submodules: false
install: true
script: "./travis.sh"
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar'
    - '$HOME/jvm'
notifications:
  email: false
  webhooks:
    - secure: "wUi4aMsY9fYk7bj3PvD/cXQ7cxXptYs/+219/Eqa44GaBOxIJotNS7ajAspDXj0IXAX7NmBqnTyOJ+2izhZYs5XG0pVBwlYKX/DD5T9KOWf+g656msCebgsZeljXRRADZppGnuTGIAilYQi7pbctq/fB56+iPNhTvZBZvE30TfFy18e7FiX+Wf5Lag+XATktJL4J+za6hSVbra+kxno+19ObizyQdodsH4SiBJezL45i2QtAbG0FVbHArFRPZZrte3HKIlteqxItqTYmkpdl1uRdn2JQz/sef9BZZ3FLIWCoeRarzJDaxotcmpnne9nPcxzDtjgJUImcCMHtYpnz4WsmHsZz3tiFBHfy/GOEVjnty167hSDMioYPw1qjSMOcINf8dqge+mPv3IZRkWwp52rSmZaW4+ugvklof6EwmIHSAV/Jg5afWSV5peTVDvBQDt5gv4Q7TVWQtOlgiI3YuTWB9wo5o/+quNC0pABYHpJEOxmQCAdqPcdz1uiTTL2nz4FHnnNO4JLyqC1bHcKBJ/BPrrQc86vMXnqsYvJcpc3QX9ciwDczrVv5DaOLWO/4WzxByG0JcmfSwDqpkB3k6qlqoPRIy2JVqgbR0Jm4bCEge63inqiM8wp41W2XDJchHfpeNYPDDPH6pYPistil4PoTn9FGalerx3ORrjqFHhw="
  on_start: always